#!/bin/bash
#PBS -j oe
#PBS -m ae
#PBS -M momoe.yoshida@my.jcu.edu.au
#PBS -N test_momoeLibrarySST
#PBS -l select=1:ncpus=1:mem=64gb
#PBS -l walltime=48:00:00
#PBS -o /gpfs01/v2/Q9157/momoe/geo_polar_blended_sst/Linux_JCUHPC/blended_home/Logs/test_momoeLibrarySST.log

# Move to the directory where the job was submitted
cd $PBS_O_WORKDIR
shopt -s expand_aliases
source /etc/profile.d/modules.sh
echo "Job identifier is $PBS_JOBID"
echo "Working directory is $PBS_O_WORKDIR"

# Clean environment
module purge
module load python3/3.11.4

# Ensure user-installed packages and scripts are visible
# Tell Python where to look for things you installed with (user)
export PATH=$HOME/.local/bin:$PATH
export PYTHONPATH=$HOME/.local/lib/python3.11/site-packages:$PYTHONPATH

# Run the test
python test_run.py
